openapi: "3.0.3"
info:
  version: 1.0.0
  title: Override Request API
servers:
  - url: http://example.com/api/v1
paths:
  /requests:  
    get:
      summary: Returns all requests or one request
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: integer
            format: int64
          description: The id of the request to return
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Request"
                  - $ref: "#/components/schemas/Requests"
                description: Returns one request or all requests
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new override request
      requestBody:
        description: Request information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewRequest"
      responses:
        '201':
          description: Created
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  # this is the changed part
  /majors:
    get:
      summary: Returns available majors in the system
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Majors"
  /minors:
    get:
      summary: Returns available minors in the system
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Minors"
  /requests/types:
    get:
      summary: Returns all possible request types
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Types"
  /departments:
    get:
      summary: Returns all the current departments
      responses:
        '200':
          description: ok
          content:
            application.json:
              schema:
                $ref: "#/components/schemas/Departments"
  /courses:
    get:
      summary: Returns courses info of a given input
      parameters:
        - in: query
          name: department
          required: true
          schema:
            type: string
          description: The department in charge of the course
        - in: query
          name: number
          required: true
          schema:
            type: integer
            format: int32
          description: the course number
        - in: query
          name: section
          required: true
          schema:
            type: integer
            format: int32
          description: the section of the course
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
  # this is the end of changed part
components:
  schemas:
    Request:
      properties:
        id:
          type: integer
          format: int64
          example: 1
        last-modified:
          type: string
          pattern: '^\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}$'
          example: "11/07/2020 22:30:47"
        last-name:
          type: string
          example: "Smith"
        first-name:
          type: string
          example: "John"
        grad-month:
          type: string
          pattern: '^\d{2}\/\d{4}$'
          example: "05/2021"
        banner-id:
          type: string
          pattern: '^001\d{6}$'
          example: "001234567"
        crn:
          type: string
          pattern: '^\d{4}\$'
          example: "1234"
        department:
          type: string
          example: "CS"
        class-number:
          type: integer
          format: int32
          example: 370
        class-standing:
          type: string
          example: "Sophomore"
        semester:
          type: string
          example: "202060"
        types:
          type: array
          items:
            type: string
          example: ["Capacity", "Prerequisites", "Other"]
        status:
          type: string
          example: "Approved"
        email:
          type: string
          pattern: '\@truman\.edu$'
          example: "jsmith@truman.edu"
        major:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics"]
        minor:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics"]
        explanation:
          type: string
          example: "I need this course to graduate"
    Requests:
      type: array
      items:
        $ref: "#/components/schemas/Request"
    NewRequest:
      properties:
        last-name:
          type: string
          example: "Smith"
        first-name:
          type: string
          example: "John"
        grad-month:
          type: string
          pattern: '^\d{2}\/\d{4}$'
          example: "05/2021"
        banner-id:
          type: string
          pattern: '^001\d{6}$'
          example: "001234567"
        crn:
          type: string
          pattern: '^\d{4}\$'
          example: "1234"
        department:
          type: string
          example: "CS"
        class-number:
          type: integer
          format: int64
          example: 370
        class-standing:
          type: string
          example: "Sophomore"
        semester:
          type: string
          example: "202060"
        types:
          type: array
          items:
            type: string
          example: ["Capacity", "Prerequisites", "Other"]
        email:
          type: string
          pattern: '\@truman\.edu$'
          example: "jsmith@truman.edu"
        major:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics"]
        minor:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics"]
        explanation:
          type: string
          example: "I need this course to graduate"
    Majors:
      properties:
        majors:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics", "Mathematics"]
    Minors:
      properties:
        minors:
          type: array
          items:
            type: string
          example: ["Computer Science", "Statistics", "Mathematics"]
    Types:
      properties:
        types:
          type: array
          items:
            type: string
          example: ["Capacity", "Prerequisites", "Time conflict", "Major restriction", "Class standing restriction", "Other"]
    Departments:
      properties:
        departments:
          type: array
          items:
            type: string
          example: ["MATH", "CS", "STAT"]
    Course:
      properties:
        title:
          type: string
          example: "Software Engineering"
        crn:
          type: string
          pattern: '^\d{4}$'
          example: "1234"
    Error:
      properties:
        code:
          type: integer
          format: int64
          example: 12
        message:
          type: string
          example: "This was an error twelve."
  
